# Generated by Django 3.1.3 on 2021-03-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210315_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Enter author', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='Add content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Enter title', max_length=200),
        ),
    ]
